### ISSUE TITLE
Use namespace specific resolv.conf file for DNS resolutions

### ISSUE THREAD

**Issue by bvk** [collarchoke/ovpn-mode#2]
Starting VPN in a namespace (using n) fails to update resolv.conf file.  As per the following links, per namespace resolv.conf file should be created in /etc/netns/NAMESPACE-NAME directory.

https://serverfault.com/questions/614574/how-to-set-dns-exclusively-for-a-network-namespace-in-linux
https://askubuntu.com/questions/501276/how-to-set-dns-exclusively-for-a-network-namespace

Debug file output:

Fri Nov 24 13:50:36 2017 /etc/openvpn/update-resolv-conf tunvpn0 1500 1585 10.8.8.9 255.255.255.0 init
dhcp-option DNS 10.8.8.1
mv: cannot move '/etc/resolvconf/run/resolv.conf_new.1662' to '/etc/resolvconf/run/resolv.conf': Device or resource busy
run-parts: /etc/resolvconf/update.d/libc exited with return code 1
Fri Nov 24 13:50:36 2017 WARNING: Failed running command (--up/--down): external program exited with error status: 1
Fri Nov 24 13:50:36 2017 Exiting due to fatal error

BTW, thank you for this simple package.

**Comment by anticomputer** [comment]
Namespace resolv.conf control is handled internally by ovpn-mode via parsing the dhcp-option from the server push notice directly (see line 631 onward). To get the desired behavior with ovpn-mode namespace handling, you should remove the up/down call to the update-resolv-conf script from the openvpn config in question if you intend to use it from a namespace. Personally I just maintain namespace-only versions of my openvpn configs that aren't intended to run globally and which do not include the system-wide update-resolv-conf up/down script calls. When running in namespace mode, ovpn-mode will create the proper resolv.conf via the aforementioned PUSH parse, in the associated /etc/netns/namespacename/ path. Since the namespace is torn down on quit/exit, there is no down-call needed either.

**Comment by anticomputer** [comment]
I'll leave this open until you confirm that works well enough for you, the alternative is a bit messy as I'd have to parse the config, check for up/down calls, replace it's sourced update-resolv-conf script with a custom version that will work with the namespace relative path, etc.

**Comment by bvk** [comment]
I see. Thanks for the explanation.  I noticed the following lines in my .ovpn file which suggests that my .opvn config files do not support creating netns namespace specific resolv.conf files.

```
...
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
...
```

If you don't mind could you share relevant lines from your .ovpn config files?  All examples I could find on internet have hardcoded netns namespace names in their paths, which I think wouldn't work in our case cause (I assume) netns namespace names would be dynamic.

**Comment by anticomputer** [comment]
You can just comment out those 2 lines and it should work, dynamic nameserver and all. ovpn-mode will already properly parse dynamic dns-option PUSH notifications and create the proper namespace resolv.conf without the need for up/down of update-resolv-conf. I use it myself with a VPN provider that pushes .onion resolvers and it works fine. So just comment out those two lines and it should work fine from namespace context through ovpn-mode.

**Comment by bvk** [comment]
Thanks for the information.

I tried commenting-out the two lines and DNS entries in the namespace mode worked as expected, but default vpn mode (i.e., command s) doesn't update the DNS entries anymore.

I can make two copies of the .ovpn files to get through, but I think the following would make the package better.

When running in default-vpn-mode one could pass `--up /etc/openvpn/update-resolv-conf --down /etc/openvpn/update-resolv-conf --down-pre` options to the openvpn *command-line* and always comment out the up/down entries the .ovpn config file.

That way, we can just have one .ovpn file work in both modes. Perhaps, we could just let users pass these extra command-line arguments through a new package-level variable depending on their .ovpn config.
