### ISSUE TITLE
Quiting an vpn session doesn't seem to update resolv.conf

### ISSUE THREAD

**Issue by bvk** [collarchoke/ovpn-mode#3]
I noticed that when I started a vpn session I see /etc/resolv.conf file is updated with an new IP

```
bvk@iron:~$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.8.8.1
nameserver 192.168.1.1
```

(for example, 10.8.8.1 in the above output) but quiting/stoping a vpn session doesn't seem to remove it. I still see the DNS entry associated with the VPN session in /etc/resolv.conf file.

**Comment by anticomputer** [comment]
Can you confirm that your down script is called correctly and resolv.conf updated if you start/quit the openvpn config in question from outside openvpn mode? Normally this shouldn't be related to ovpn-mode's handling of resolv.conf but rather an issue with your actual openvpn config's usage of update-resolv-conf. In testing here resolv.conf updates up/down work fine on start/quit of openvpn configs from ovpn-mode.

**Comment by bvk** [comment]
I think something was wrong on my host because `openvpn --config file.ovpn` also did not clean the DNS entry. But, after a reboot everything seems to be working file. My apologies for the unnecessary bug report; I am closing this issue.
