### ISSUE TITLE
Backup .ovpn file are also listed

### ISSUE THREAD

**Issue by bvk** [collarchoke/ovpn-mode#4]
When a directory with .ovpn files is selected for listing, backup files must be ignored from the list. See the attached picture.

![2fe88da2-9a3d-4d63-8347-471b3aec6e7e](https://user-images.githubusercontent.com/52023/33235416-f28045fe-d1ec-11e7-882e-d1b629996c63.JPG)

**Comment by anticomputer** [comment]
fixed in latest commit.
